const { chromium } = require('/opt/node-tools/node_modules/playwright');
(async () => { const b = await chromium.launch(); const ctx = await b.newContext({ viewport: { width: 870, height: 401 }, serviceWorkers: 'block', deviceScaleFactor: 1, isMobile: true, hasTouch: true }); const p = await ctx.newPage();
  await p.goto('http://localhost:8765/#debug'); await p.evaluate(() => { localStorage.clear(); localStorage.setItem('chungo.tut', '1'); localStorage.setItem('chungo.meta', JSON.stringify({ firsts: { tutDone: 1 }, runN: 5, tips: { w_hwando: 1, edge: 1, chungo: 1 } })); localStorage.setItem('chungo.run', JSON.stringify({ v: 2, seed: 7, dateKey: 'x', m: 3, cycle: 0, cp: -1, dead: [], breath: 5, qi: 0, time: 0, deaths: 0, kills: 0, strikes: 0, slashes: 0, perks: [], weapon: 'hwando' })); });
  await p.reload(); await p.waitForFunction(() => document.getElementById('loading').hidden, null, { timeout: 90000 });
  await p.evaluate(() => document.getElementById('bContinue').click()); await p.waitForTimeout(300); await p.click('#bEnter'); await p.waitForFunction(() => __dbg.state === 'play', null, { timeout: 60000 }); await p.evaluate(() => { __dbg.P.invT = 999; });
  await p.waitForTimeout(2000);
  const r = await p.evaluate(() => new Promise(res => { const C = CanvasRenderingContext2D.prototype, names = ['drawImage', 'fill', 'stroke', 'fillRect', 'fillText', 'createLinearGradient', 'createRadialGradient', 'createPattern', 'save'], orig = {}, cnt = {}, area = {};
    for (const n of names) { orig[n] = C[n]; C[n] = function (...a) { const k = n + ' ' + (new Error().stack.split('\n')[2].trim().match(/at (\S+) .*:(\d+):\d+/) || []).slice(1,3).join(':'); cnt[k] = (cnt[k] || 0) + 1; if (n === 'drawImage') { const m = this.getTransform(); const w = a.length > 5 ? a[7] : a.length > 3 ? a[3] : a[0].width, h = a.length > 5 ? a[8] : a.length > 3 ? a[4] : a[0].height; area[k] = (area[k] || 0) + Math.abs(w * h * m.a * m.d); } if (n === 'fillRect') { const m = this.getTransform(); area[k] = (area[k] || 0) + Math.abs(a[2] * a[3] * m.a * m.d); } return orig[n].apply(this, a); }; }
    requestAnimationFrame(() => requestAnimationFrame(() => { for (const n of names) C[n] = orig[n]; res(Object.entries(cnt).map(([k, v]) => [k, v, Math.round((area[k] || 0) / 1000)]).sort((a, b) => b[2] - a[2] || b[1] - a[1])); })); }));
  const scr = 870 * 401 / 1000; console.log('screen kpx', scr); r.slice(0, 30).forEach(x => console.log(x.join('  ')));
  await b.close(); })();
